// Golden-age cartoon catalog, grouped into themed rows. Each entry is
// { t: title, y: year, type }. Titles are resolved to IMDb ids + posters at
// runtime via TMDB search (year disambiguates). Add or remove lines freely.
module.exports = {
  // The Cartoon Network "Cartoon Cartoons" era + modern originals
  cn_originals: [
    { t: "2 Stupid Dogs", y: 1993, type: "series" },
    { t: "Dexter's Laboratory", y: 1996, type: "series" },
    { t: "Johnny Bravo", y: 1997, type: "series" },
    { t: "Cow and Chicken", y: 1997, type: "series" },
    { t: "I Am Weasel", y: 1997, type: "series" },
    { t: "The Powerpuff Girls", y: 1998, type: "series" },
    { t: "Ed, Edd n Eddy", y: 1999, type: "series" },
    { t: "Courage the Cowardly Dog", y: 1999, type: "series" },
    { t: "Mike, Lu & Og", y: 1999, type: "series" },
    { t: "Sheep in the Big City", y: 2000, type: "series" },
    { t: "Time Squad", y: 2001, type: "series" },
    { t: "Samurai Jack", y: 2001, type: "series" },
    { t: "Grim & Evil", y: 2001, type: "series" },
    { t: "Whatever Happened to... Robot Jones?", y: 2002, type: "series" },
    { t: "Codename: Kids Next Door", y: 2002, type: "series" },
    { t: "The Grim Adventures of Billy and Mandy", y: 2003, type: "series" },
    { t: "Star Wars: Clone Wars", y: 2003, type: "series" },
    { t: "Evil Con Carne", y: 2003, type: "series" },
    { t: "Xiaolin Showdown", y: 2003, type: "series" },
    { t: "Megas XLR", y: 2004, type: "series" },
    { t: "Foster's Home for Imaginary Friends", y: 2004, type: "series" },
    { t: "Hi Hi Puffy AmiYumi", y: 2004, type: "series" },
    { t: "Camp Lazlo", y: 2005, type: "series" },
    { t: "The Life and Times of Juniper Lee", y: 2005, type: "series" },
    { t: "My Gym Partner's a Monkey", y: 2005, type: "series" },
    { t: "Ben 10", y: 2005, type: "series" },
    { t: "Robotboy", y: 2005, type: "series" },
    { t: "Squirrel Boy", y: 2006, type: "series" },
    { t: "Class of 3000", y: 2006, type: "series" },
    { t: "Chowder", y: 2007, type: "series" },
    { t: "Ben 10: Alien Force", y: 2008, type: "series" },
    { t: "The Marvelous Misadventures of Flapjack", y: 2008, type: "series" },
    { t: "The Secret Saturdays", y: 2008, type: "series" },
    { t: "Chop Socky Chooks", y: 2008, type: "series" },
    { t: "Generator Rex", y: 2010, type: "series" },
    { t: "Sym-Bionic Titan", y: 2010, type: "series" },
    { t: "Little Dracula", y: 1991, type: "series" },
    { t: "Adventure Time", y: 2010, type: "series" },
    { t: "Regular Show", y: 2010, type: "series" },
    { t: "The Amazing World of Gumball", y: 2011, type: "series" },
    { t: "Uncle Grandpa", y: 2013, type: "series" },
    { t: "Steven Universe", y: 2013, type: "series" },
    { t: "Teen Titans Go!", y: 2013, type: "series" },
    { t: "Clarence", y: 2014, type: "series" },
    { t: "We Bare Bears", y: 2015, type: "series" },
  ],

  // Hanna-Barbera golden age (Boomerang staples)
  hanna_barbera: [
    { t: "Huckleberry Hound", y: 1958, type: "series" },
    { t: "Quick Draw McGraw", y: 1959, type: "series" },
    { t: "The Flintstones", y: 1960, type: "series" },
    { t: "Top Cat", y: 1961, type: "series" },
    { t: "The Yogi Bear Show", y: 1961, type: "series" },
    { t: "The Jetsons", y: 1962, type: "series" },
    { t: "Jonny Quest", y: 1964, type: "series" },
    { t: "Magilla Gorilla", y: 1964, type: "series" },
    { t: "Atom Ant", y: 1965, type: "series" },
    { t: "Secret Squirrel", y: 1965, type: "series" },
    { t: "Space Ghost", y: 1966, type: "series" },
    { t: "Frankenstein Jr. and The Impossibles", y: 1966, type: "series" },
    { t: "The Herculoids", y: 1967, type: "series" },
    { t: "Wacky Races", y: 1968, type: "series" },
    { t: "Scooby-Doo, Where Are You!", y: 1969, type: "series" },
    { t: "Dastardly and Muttley in Their Flying Machines", y: 1969, type: "series" },
    { t: "Josie and the Pussycats", y: 1970, type: "series" },
    { t: "Help!... It's the Hair Bear Bunch!", y: 1971, type: "series" },
    { t: "The New Scooby-Doo Movies", y: 1972, type: "series" },
    { t: "Sealab 2020", y: 1972, type: "series" },
    { t: "Hong Kong Phooey", y: 1974, type: "series" },
    { t: "Jabberjaw", y: 1976, type: "series" },
    { t: "Captain Caveman and the Teen Angels", y: 1977, type: "series" },
    { t: "Scooby-Doo and Scrappy-Doo", y: 1979, type: "series" },
    { t: "The Smurfs", y: 1981, type: "series" },
    { t: "Snorks", y: 1984, type: "series" },
    { t: "The Real Adventures of Jonny Quest", y: 1996, type: "series" },
  ],

  // Looney Tunes & Warner Bros animation
  looney_wb: [
    { t: "The Bugs Bunny Show", y: 1960, type: "series" },
    { t: "Tom and Jerry", y: 1965, type: "series" },
    { t: "Tiny Toon Adventures", y: 1990, type: "series" },
    { t: "Taz-Mania", y: 1991, type: "series" },
    { t: "Animaniacs", y: 1993, type: "series" },
    { t: "The Sylvester & Tweety Mysteries", y: 1995, type: "series" },
    { t: "Pinky and the Brain", y: 1995, type: "series" },
    { t: "Road Rovers", y: 1996, type: "series" },
    { t: "Histeria!", y: 1998, type: "series" },
    { t: "Baby Looney Tunes", y: 2002, type: "series" },
    { t: "Duck Dodgers", y: 2003, type: "series" },
    { t: "Loonatics Unleashed", y: 2005, type: "series" },
    { t: "The Looney Tunes Show", y: 2011, type: "series" },
  ],

  // DC & Marvel animated heroes
  dc_marvel: [
    { t: "X-Men: The Animated Series", y: 1992, type: "series" },
    { t: "Batman: The Animated Series", y: 1992, type: "series" },
    { t: "Spider-Man: The Animated Series", y: 1994, type: "series" },
    { t: "Iron Man", y: 1994, type: "series" },
    { t: "Fantastic Four", y: 1994, type: "series" },
    { t: "Superman: The Animated Series", y: 1996, type: "series" },
    { t: "The Incredible Hulk", y: 1996, type: "series" },
    { t: "Silver Surfer", y: 1998, type: "series" },
    { t: "Spider-Man Unlimited", y: 1999, type: "series" },
    { t: "Batman Beyond", y: 1999, type: "series" },
    { t: "X-Men: Evolution", y: 2000, type: "series" },
    { t: "Static Shock", y: 2000, type: "series" },
    { t: "Justice League", y: 2001, type: "series" },
    { t: "Teen Titans", y: 2003, type: "series" },
    { t: "The Batman", y: 2004, type: "series" },
    { t: "Justice League Unlimited", y: 2004, type: "series" },
    { t: "Krypto the Superdog", y: 2005, type: "series" },
    { t: "Legion of Super Heroes", y: 2006, type: "series" },
    { t: "Fantastic Four: World's Greatest Heroes", y: 2006, type: "series" },
    { t: "The Spectacular Spider-Man", y: 2008, type: "series" },
    { t: "Wolverine and the X-Men", y: 2008, type: "series" },
    { t: "Batman: The Brave and the Bold", y: 2008, type: "series" },
    { t: "Young Justice", y: 2010, type: "series" },
    { t: "The Avengers: Earth's Mightiest Heroes", y: 2010, type: "series" },
  ],

  // 80s/90s action legends
  action_80s: [
    { t: "He-Man and the Masters of the Universe", y: 1983, type: "series" },
    { t: "Inspector Gadget", y: 1983, type: "series" },
    { t: "Dungeons & Dragons", y: 1983, type: "series" },
    { t: "Voltron", y: 1984, type: "series" },
    { t: "The Transformers", y: 1984, type: "series" },
    { t: "Muppet Babies", y: 1984, type: "series" },
    { t: "She-Ra: Princess of Power", y: 1985, type: "series" },
    { t: "G.I. Joe: A Real American Hero", y: 1985, type: "series" },
    { t: "M.A.S.K.", y: 1985, type: "series" },
    { t: "Jem", y: 1985, type: "series" },
    { t: "ThunderCats", y: 1985, type: "series" },
    { t: "SilverHawks", y: 1986, type: "series" },
    { t: "The Real Ghostbusters", y: 1986, type: "series" },
    { t: "DuckTales", y: 1987, type: "series" },
    { t: "BraveStarr", y: 1987, type: "series" },
    { t: "Teenage Mutant Ninja Turtles", y: 1987, type: "series" },
    { t: "Dino-Riders", y: 1988, type: "series" },
    { t: "Beetlejuice", y: 1989, type: "series" },
    { t: "Captain Planet and the Planeteers", y: 1990, type: "series" },
    { t: "Exosquad", y: 1993, type: "series" },
    { t: "Biker Mice from Mars", y: 1993, type: "series" },
    { t: "SWAT Kats: The Radical Squadron", y: 1993, type: "series" },
    { t: "The Tick", y: 1994, type: "series" },
    { t: "Gargoyles", y: 1994, type: "series" },
  ],
};

// --- MOVIES (CN specials, Scooby features, classic cartoon films) ---
module.exports.scooby_movies = [
  { t: "Scooby-Doo on Zombie Island", y: 1998, type: "movie" },
  { t: "Scooby-Doo! and the Witch's Ghost", y: 1999, type: "movie" },
  { t: "Scooby-Doo and the Alien Invaders", y: 2000, type: "movie" },
  { t: "Scooby-Doo and the Cyber Chase", y: 2001, type: "movie" },
  { t: "Scooby-Doo! and the Legend of the Vampire", y: 2003, type: "movie" },
  { t: "Scooby-Doo! and the Monster of Mexico", y: 2003, type: "movie" },
  { t: "Scooby-Doo! and the Loch Ness Monster", y: 2004, type: "movie" },
  { t: "Aloha, Scooby-Doo!", y: 2005, type: "movie" },
  { t: "Scooby-Doo! in Where's My Mummy?", y: 2005, type: "movie" },
  { t: "Scooby-Doo! Pirates Ahoy!", y: 2006, type: "movie" },
  { t: "Chill Out, Scooby-Doo!", y: 2007, type: "movie" },
  { t: "Scooby-Doo! and the Goblin King", y: 2008, type: "movie" },
  { t: "Scooby-Doo! and the Samurai Sword", y: 2009, type: "movie" },
  { t: "Scooby-Doo! Abracadabra-Doo", y: 2010, type: "movie" },
  { t: "Scooby-Doo! Camp Scare", y: 2010, type: "movie" },
];

module.exports.cn_movies = [
  { t: "The Powerpuff Girls Movie", y: 2002, type: "movie" },
  { t: "Ben 10: Secret of the Omnitrix", y: 2007, type: "movie" },
  { t: "Billy & Mandy's Big Boogey Adventure", y: 2007, type: "movie" },
  { t: "Ben 10: Destroy All Aliens", y: 2012, type: "movie" },
  { t: "Regular Show: The Movie", y: 2015, type: "movie" },
  { t: "Steven Universe: The Movie", y: 2019, type: "movie" },
  { t: "We Bare Bears: The Movie", y: 2020, type: "movie" },
];

module.exports.classic_movies = [
  { t: "Hey There, It's Yogi Bear!", y: 1964, type: "movie" },
  { t: "The Man Called Flintstone", y: 1966, type: "movie" },
  { t: "Charlotte's Web", y: 1973, type: "movie" },
  { t: "Jetsons: The Movie", y: 1990, type: "movie" },
  { t: "Tom and Jerry: The Movie", y: 1992, type: "movie" },
  { t: "Space Jam", y: 1996, type: "movie" },
  { t: "The Iron Giant", y: 1999, type: "movie" },
  { t: "Looney Tunes: Back in Action", y: 2003, type: "movie" },
];

// More of the classic CN vault (Hanna-Barbera library + acquired staples)
module.exports.extra_classics = [
  { t: "Pixie and Dixie and Mr. Jinks", y: 1958, type: "series" },
  { t: "Augie Doggie and Doggie Daddy", y: 1959, type: "series" },
  { t: "Snagglepuss", y: 1961, type: "series" },
  { t: "Wally Gator", y: 1962, type: "series" },
  { t: "Peter Potamus", y: 1964, type: "series" },
  { t: "Ricochet Rabbit & Droop-a-Long", y: 1964, type: "series" },
  { t: "Squiddly Diddly", y: 1965, type: "series" },
  { t: "Moby Dick and Mighty Mightor", y: 1967, type: "series" },
  { t: "Shazzan", y: 1967, type: "series" },
  { t: "The Banana Splits Adventure Hour", y: 1968, type: "series" },
  { t: "The Funky Phantom", y: 1971, type: "series" },
  { t: "Wait Till Your Father Gets Home", y: 1972, type: "series" },
  { t: "Super Friends", y: 1973, type: "series" },
  { t: "Speed Buggy", y: 1973, type: "series" },
  { t: "The Great Grape Ape Show", y: 1975, type: "series" },
  { t: "Clue Club", y: 1976, type: "series" },
  { t: "Dynomutt, Dog Wonder", y: 1976, type: "series" },
  { t: "Godzilla", y: 1978, type: "series" },
  { t: "Plastic Man", y: 1979, type: "series" },
  { t: "Thundarr the Barbarian", y: 1980, type: "series" },
  { t: "Richie Rich", y: 1980, type: "series" },
  { t: "Pac-Man", y: 1982, type: "series" },
  { t: "Alvin and the Chipmunks", y: 1983, type: "series" },
  { t: "Heathcliff", y: 1984, type: "series" },
  { t: "Galtar and the Golden Lance", y: 1985, type: "series" },
  { t: "Robotech", y: 1985, type: "series" },
  { t: "Centurions", y: 1986, type: "series" },
  { t: "Pound Puppies", y: 1986, type: "series" },
  { t: "Sky Commanders", y: 1987, type: "series" },
  { t: "Fantastic Max", y: 1988, type: "series" },
  { t: "The Pirates of Dark Water", y: 1991, type: "series" },
  { t: "James Bond Jr.", y: 1991, type: "series" },
  { t: "ReBoot", y: 1994, type: "series" },
  { t: "Jackie Chan Adventures", y: 2000, type: "series" },
  { t: "The Cramp Twins", y: 2001, type: "series" },
  { t: "Mucha Lucha", y: 2002, type: "series" },
  { t: "Code Lyoko", y: 2003, type: "series" },
  { t: "6teen", y: 2004, type: "series" },
  { t: "Johnny Test", y: 2005, type: "series" },
  { t: "Total Drama Island", y: 2007, type: "series" },
  { t: "Storm Hawks", y: 2007, type: "series" },
  { t: "George of the Jungle", y: 2007, type: "series" },
  { t: "Skunk Fu!", y: 2007, type: "series" },
  { t: "The Garfield Show", y: 2009, type: "series" },
  { t: "Casper's Scare School", y: 2009, type: "series" },
  { t: "Hero: 108", y: 2010, type: "series" },
  { t: "Ninjago", y: 2011, type: "series" },
  { t: "Sonic Boom", y: 2014, type: "series" },
];

// Toonami / anime block
module.exports.toonami = [
  { t: "Dragon Ball", y: 1986, type: "series" },
  { t: "Dragon Ball Z", y: 1989, type: "series" },
  { t: "Dragon Ball GT", y: 1996, type: "series" },
  { t: "Sailor Moon", y: 1992, type: "series" },
  { t: "Ronin Warriors", y: 1988, type: "series" },
  { t: "Tenchi Muyo!", y: 1992, type: "series" },
  { t: "Yu Yu Hakusho", y: 1992, type: "series" },
  { t: "Mobile Suit Gundam Wing", y: 1995, type: "series" },
  { t: "Rurouni Kenshin", y: 1996, type: "series" },
  { t: "Cardcaptor Sakura", y: 1998, type: "series" },
  { t: "Outlaw Star", y: 1998, type: "series" },
  { t: "The Big O", y: 1999, type: "series" },
  { t: "One Piece", y: 1999, type: "series" },
  { t: "Zoids: Chaotic Century", y: 1999, type: "series" },
  { t: "Pokémon", y: 1997, type: "series" },
  { t: "Hamtaro", y: 2000, type: "series" },
  { t: "Yu-Gi-Oh!", y: 2000, type: "series" },
  { t: "Shaman King", y: 2001, type: "series" },
  { t: "The Prince of Tennis", y: 2001, type: "series" },
  { t: "Duel Masters", y: 2002, type: "series" },
  { t: "Naruto", y: 2002, type: "series" },
  { t: "Transformers: Armada", y: 2002, type: "series" },
  { t: ".hack//Sign", y: 2002, type: "series" },
  { t: "Astro Boy", y: 2003, type: "series" },
  { t: "Bobobo-bo Bo-bobo", y: 2003, type: "series" },
  { t: "Zatch Bell!", y: 2003, type: "series" },
  { t: "Yu-Gi-Oh! GX", y: 2004, type: "series" },
  { t: "MÄR", y: 2005, type: "series" },
  { t: "IGPX", y: 2005, type: "series" },
  { t: "Bakugan Battle Brawlers", y: 2007, type: "series" },
  { t: "Beyblade: Metal Fusion", y: 2009, type: "series" },
];

// Saturday-morning & syndicated classics (Fox Kids, Kids' WB, first-run syndication)
module.exports.saturday_morning = [
  { t: "Teenage Mutant Ninja Turtles", y: 1987, type: "series" },
  { t: "The Real Ghostbusters", y: 1986, type: "series" },
  { t: "Filmation's Ghostbusters", y: 1986, type: "series" },
  { t: "C.O.P.S.", y: 1988, type: "series" },
  { t: "Denver, the Last Dinosaur", y: 1988, type: "series" },
  { t: "Captain N: The Game Master", y: 1989, type: "series" },
  { t: "The Super Mario Bros. Super Show!", y: 1989, type: "series" },
  { t: "The Legend of Zelda", y: 1989, type: "series" },
  { t: "Bobby's World", y: 1990, type: "series" },
  { t: "Super Mario World", y: 1991, type: "series" },
  { t: "Where's Waldo?", y: 1991, type: "series" },
  { t: "ProStars", y: 1991, type: "series" },
  { t: "X-Men: The Animated Series", y: 1992, type: "series" },
  { t: "Eek! The Cat", y: 1992, type: "series" },
  { t: "Wild West C.O.W.-Boys of Moo Mesa", y: 1992, type: "series" },
  { t: "Sonic the Hedgehog", y: 1993, type: "series" },
  { t: "Adventures of Sonic the Hedgehog", y: 1993, type: "series" },
  { t: "Double Dragon", y: 1993, type: "series" },
  { t: "Mighty Max", y: 1993, type: "series" },
  { t: "The Tick", y: 1994, type: "series" },
  { t: "Spider-Man: The Animated Series", y: 1994, type: "series" },
  { t: "Street Sharks", y: 1994, type: "series" },
  { t: "Mega Man", y: 1994, type: "series" },
  { t: "Earthworm Jim", y: 1995, type: "series" },
  { t: "The Mask: The Animated Series", y: 1995, type: "series" },
  { t: "Freakazoid!", y: 1995, type: "series" },
  { t: "Jumanji", y: 1996, type: "series" },
  { t: "Beast Wars: Transformers", y: 1996, type: "series" },
  { t: "Men in Black: The Series", y: 1997, type: "series" },
  { t: "Extreme Ghostbusters", y: 1997, type: "series" },
  { t: "Godzilla: The Series", y: 1998, type: "series" },
  { t: "Digimon: Digital Monsters", y: 1999, type: "series" },
];

// The Disney Afternoon & Disney animated block
module.exports.disney_afternoon = [
  { t: "Adventures of the Gummi Bears", y: 1985, type: "series" },
  { t: "DuckTales", y: 1987, type: "series" },
  { t: "Chip 'n Dale: Rescue Rangers", y: 1989, type: "series" },
  { t: "TaleSpin", y: 1990, type: "series" },
  { t: "Darkwing Duck", y: 1991, type: "series" },
  { t: "Goof Troop", y: 1992, type: "series" },
  { t: "Raw Toonage", y: 1992, type: "series" },
  { t: "Bonkers", y: 1993, type: "series" },
  { t: "Marsupilami", y: 1993, type: "series" },
  { t: "Aladdin", y: 1994, type: "series" },
  { t: "Gargoyles", y: 1994, type: "series" },
  { t: "The Lion King's Timon & Pumbaa", y: 1995, type: "series" },
  { t: "Quack Pack", y: 1996, type: "series" },
  { t: "Jungle Cubs", y: 1996, type: "series" },
  { t: "Recess", y: 1997, type: "series" },
  { t: "101 Dalmatians: The Series", y: 1997, type: "series" },
  { t: "Pepper Ann", y: 1997, type: "series" },
  { t: "Hercules", y: 1998, type: "series" },
  { t: "Mickey Mouse Works", y: 1999, type: "series" },
  { t: "Buzz Lightyear of Star Command", y: 2000, type: "series" },
  { t: "The Weekenders", y: 2000, type: "series" },
  { t: "House of Mouse", y: 2001, type: "series" },
  { t: "The Legend of Tarzan", y: 2001, type: "series" },
  { t: "Kim Possible", y: 2002, type: "series" },
  { t: "Lilo & Stitch: The Series", y: 2003, type: "series" },
  { t: "American Dragon: Jake Long", y: 2005, type: "series" },
  { t: "Phineas and Ferb", y: 2007, type: "series" },
];
